-- -- /*Addresses*/
-- insert into address (street, city, state) values ('Omladinska 19', 'Novi Sad', 'Srbija');
-- insert into address (street, city, state) values ('Jevrejska 44', 'Beograd', 'Srbija');
-- insert into address (street, city, state) values ('Bulevar kralja Aleksandra 37', 'Beograd', 'Srbija');
-- insert into address (street, city, state) values ('Fruskogorksa 14', 'Novi Sad', 'Srbija');
-- insert into address (street, city, state) values ('Bulevar oslobodjenja 119', 'Novi Sad', 'Srbija');
-- insert into address (street, city, state) values ('Somborska 39', 'Novi Sad', 'Srbija');
-- insert into address (street, city, state) values ('Lasla Gala 4', 'Beograd', 'Srbija');
-- insert into address (street, city, state) values ('Bulevar kralja Petra 137', 'Beograd', 'Srbija');
-- insert into address (street, city, state) values ('Fruskogorksa 60', 'Novi Sad', 'Srbija');
-- insert into address (street, city, state) values ('Mise Dimitrijevica 19', 'Novi Sad', 'Srbija');
--
--
-- insert into my_user (email, first_name, last_name, password, phone_number, address_id, deleted) values ('pera@gmail.com', 'Petar', 'Peric', '$2a$10$vxfy.kTR4mQxDTIQ6LmeCuoea46hQ9KmeBTTSW4BQay4QD60nXo5K', '124890', 1, false);
--
-- insert into client (client_category, penal, id) values ('CASUAL_CLIENT', 3, 1);